#!/bin/bash

if ! [ -d ~/.config ]; then
   echo "creating .config folder"
   mkdir ~/.config
fi

if ! [ -d ~/.config/rerobapp ]; then
   echo "creating .config/rerobapp folder"
   mkdir ~/.config/rerobapp
fi

if [ -f rerobapp.conf ]; then
   rm rerobapp.conf
fi

no_touch_here/start.conf > ~/.config/rerobapp/rerobapp.conf
chmod +x ~/.config/rerobapp/rerobapp.conf

ln -s ~/.config/rerobapp/rerobapp.conf . 

cat rerobapp.conf

if [ -f ~/.config/rerobapp/rerobapp.conf ]; then
   source ~/.config/rerobapp/rerobapp.conf
else
   echo "Loading rerobapp.conf local"
   source rerobapp.conf
fi